//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtendaanceProject.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int id { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_schedule { get; set; }
        public Nullable<int> id_atendance { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual AtendanceType AtendanceType { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Student Student { get; set; }
    }
}
